server.port: 8080

spring:
  datasource:
    url:jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate

  username: postgres
  password: master@
  jpa:
    show-sql: true
    hibernate: update
    properties:
      hibernate.format_sql: true

      logging:
        level:
          org:
            hibernate:
              type: trace